version: "2"

services:
  app:
    image: golang:1.10.3-alpine
    ports: 
      - 8080:8080
    volumes:
      - .:/go/src/github.com/rahardiandj/ethermining
    working_dir: /go/src/github.com/rahardiandj/ethermining
    command: go run main.go
    links:
      - mongodb_ethermining
    depends_on:
      - mongodb_ethermining
  mongodb_ethermining:
    image: mongo:latest
    container_name: "mongodb_ethermining"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null